"""create company ,location and employee tables

Revision ID: 751dec83e958
Revises: 
Create Date: 2026-02-11 12:53:28.805396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '751dec83e958'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('company_uuid', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('company_registration_no', sa.String(length=100), nullable=False, comment='company registration no'),
    sa.Column('company_type', sa.String(length=100), server_default='private', nullable=False, comment='company type like private,public,ngo,govt etc'),
    sa.Column('company_type_meta', sa.String(length=100), nullable=False, comment='company like software,manufacturing,education etc'),
    sa.Column('company_web', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('company_logo', sa.String(length=255), nullable=True, comment='company logo image'),
    sa.Column('comapny_email', sa.String(length=255), nullable=False, comment='comapny email'),
    sa.Column('company_contact_no', sa.String(length=255), nullable=False, comment='company contact no'),
    sa.Column('company_gst_no', sa.String(length=255), nullable=True),
    sa.Column('company_pan_no', sa.String(length=255), nullable=False),
    sa.Column('company_tin_no', sa.String(length=255), nullable=False),
    sa.Column('company_cin_no', sa.String(length=255), nullable=False),
    sa.Column('company_meta', mysql.JSON(), nullable=True, comment='json detail for other info'),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', mysql.TINYINT(), server_default='0', nullable=False, comment='0 for inactive,1 for active ,2 for hold, 3 for deleted'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_registration_no')
    )
    op.create_index('company_company_name_company_uuid_index', 'companies', ['company_name', 'company_uuid'], unique=False)
    op.create_index('company_id_index', 'companies', ['id'], unique=False)
    op.create_table('company_action',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('action_uuid', sa.String(length=36), nullable=False),
    sa.Column('company_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('action_name', sa.String(length=25), nullable=False),
    sa.Column('is_active', mysql.TINYINT(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_action_comp_uuid', 'company_action', ['company_id', 'action_uuid'], unique=False)
    op.create_table('company_department',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('company_id', mysql.BIGINT(unsigned=True), nullable=False, comment='company table id'),
    sa.Column('department_uuid', sa.String(length=36), nullable=False),
    sa.Column('department_name', sa.String(length=50), nullable=False, comment='department name like HR,PAYROLL etc'),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('is_active_department', mysql.TINYINT(), server_default='0', nullable=False, comment='0 for inactive,1 for active ,2 for hold, 3 for deleted'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('company_department_company_id_index', 'company_department', ['company_id'], unique=False)
    op.create_index('company_department_department_name_index', 'company_department', ['department_name'], unique=False)
    op.create_index('company_department_department_uuid_index', 'company_department', ['department_uuid'], unique=False)
    op.create_table('company_designation',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('company_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('designation_uuid', sa.String(length=36), nullable=False),
    sa.Column('designation_name', sa.String(length=50), nullable=False, comment='HR, PAYROLL etc'),
    sa.Column('designation_level', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cd_company', 'company_designation', ['company_id'], unique=False)
    op.create_index('idx_cd_name', 'company_designation', ['designation_name'], unique=False)
    op.create_index('idx_cd_uuid', 'company_designation', ['designation_uuid'], unique=False)
    op.create_table('company_job_type',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('job_type_uuid', sa.String(length=36), nullable=False),
    sa.Column('company_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('job_type', sa.String(length=25), nullable=False, comment='full time, part time'),
    sa.Column('is_active', mysql.TINYINT(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_type_comp_uuid', 'company_job_type', ['company_id', 'job_type_uuid'], unique=False)
    op.create_table('company_work_type',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('work_type_uuid', sa.String(length=36), nullable=False),
    sa.Column('company_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('work_type', sa.String(length=25), nullable=False, comment='remote, hybrid, onsite'),
    sa.Column('is_active', mysql.TINYINT(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_work_type_comp_uuid', 'company_work_type', ['company_id', 'work_type_uuid'], unique=False)
    op.create_table('locations',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('company_id', mysql.BIGINT(unsigned=True), nullable=False, comment='companies table id'),
    sa.Column('location_uuid', sa.String(length=36), nullable=False),
    sa.Column('is_primary_address', sa.Boolean(), server_default='0', nullable=False, comment='1 for primery ,0 for non'),
    sa.Column('location_address', mysql.MEDIUMTEXT(), nullable=False, comment='location address'),
    sa.Column('location_city', sa.String(length=50), nullable=False),
    sa.Column('location_state', sa.String(length=50), nullable=False),
    sa.Column('location_pin_code', sa.String(length=15), nullable=False),
    sa.Column('location_country', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('is_active_location', mysql.TINYINT(), server_default='0', nullable=False, comment='0 for inactive,1 for active ,2 for hold, 3 for deleted'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('locations_company_id_index', 'locations', ['company_id'], unique=False)
    op.create_index('locations_location_uuid_index', 'locations', ['location_uuid'], unique=False)
    op.create_table('company_location_department',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('company_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('location_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('department_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('is_active_location_department', mysql.TINYINT(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['company_department.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cld_company', 'company_location_department', ['company_id'], unique=False)
    op.create_index('idx_cld_department', 'company_location_department', ['department_id'], unique=False)
    op.create_index('idx_cld_location', 'company_location_department', ['location_id'], unique=False)
    op.create_table('employee',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('company_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('location_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('location_department_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('emp_uuid', sa.String(length=36), nullable=False),
    sa.Column('emp_code', sa.String(length=50), nullable=False),
    sa.Column('emp_contact_no', sa.String(length=25), nullable=False),
    sa.Column('emp_official_email', sa.String(length=20), nullable=False),
    sa.Column('date_of_joining', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_of_leaving', sa.DateTime(timezone=True), nullable=True),
    sa.Column('emp_status', mysql.TINYINT(), server_default='0', nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['location_department_id'], ['company_location_department.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_emp_company', 'employee', ['company_id'], unique=False)
    op.create_index('idx_emp_loc_dept', 'employee', ['location_department_id'], unique=False)
    op.create_index('idx_emp_location', 'employee', ['location_id'], unique=False)
    op.create_index('idx_emp_uuid', 'employee', ['emp_uuid'], unique=False)
    op.create_table('company_emp_action',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('company_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('location_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('company_action_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('emp_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('is_active_shift_location', mysql.TINYINT(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['company_action_id'], ['company_action.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['emp_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_profile',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('emp_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female', 'Other'), nullable=False),
    sa.Column('mobile_no', mysql.BIGINT(), nullable=False),
    sa.Column('emp_dob', sa.Date(), nullable=False),
    sa.Column('emp_email', sa.String(length=50), nullable=False),
    sa.Column('blood_group', sa.String(length=5), nullable=False),
    sa.Column('emp_marital_status', mysql.TINYINT(), server_default='0', nullable=False),
    sa.Column('emp_profile_status', mysql.TINYINT(), server_default='0', nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['emp_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ep_emp', 'employee_profile', ['emp_id'], unique=False)
    op.create_index('idx_ep_fname', 'employee_profile', ['first_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ep_fname', table_name='employee_profile')
    op.drop_index('idx_ep_emp', table_name='employee_profile')
    op.drop_table('employee_profile')
    op.drop_table('company_emp_action')
    op.drop_index('idx_emp_uuid', table_name='employee')
    op.drop_index('idx_emp_location', table_name='employee')
    op.drop_index('idx_emp_loc_dept', table_name='employee')
    op.drop_index('idx_emp_company', table_name='employee')
    op.drop_table('employee')
    op.drop_index('idx_cld_location', table_name='company_location_department')
    op.drop_index('idx_cld_department', table_name='company_location_department')
    op.drop_index('idx_cld_company', table_name='company_location_department')
    op.drop_table('company_location_department')
    op.drop_index('locations_location_uuid_index', table_name='locations')
    op.drop_index('locations_company_id_index', table_name='locations')
    op.drop_table('locations')
    op.drop_index('idx_work_type_comp_uuid', table_name='company_work_type')
    op.drop_table('company_work_type')
    op.drop_index('idx_job_type_comp_uuid', table_name='company_job_type')
    op.drop_table('company_job_type')
    op.drop_index('idx_cd_uuid', table_name='company_designation')
    op.drop_index('idx_cd_name', table_name='company_designation')
    op.drop_index('idx_cd_company', table_name='company_designation')
    op.drop_table('company_designation')
    op.drop_index('company_department_department_uuid_index', table_name='company_department')
    op.drop_index('company_department_department_name_index', table_name='company_department')
    op.drop_index('company_department_company_id_index', table_name='company_department')
    op.drop_table('company_department')
    op.drop_index('idx_action_comp_uuid', table_name='company_action')
    op.drop_table('company_action')
    op.drop_index('company_id_index', table_name='companies')
    op.drop_index('company_company_name_company_uuid_index', table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
