"""changes in table company table add country

Revision ID: 9513058d0621
Revises: dcdb69577453
Create Date: 2026-02-13 17:12:31.512236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9513058d0621'
down_revision: Union[str, Sequence[str], None] = 'dcdb69577453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('company_country', sa.String(length=50), nullable=True, comment='company country'))
    op.drop_column('companies', 'comapany_country')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('comapany_country', mysql.VARCHAR(length=50), nullable=False, comment='company country'))
    op.drop_column('companies', 'company_country')
    # ### end Alembic commands ###
