"""changes in table

Revision ID: d22e31982add
Revises: 751dec83e958
Create Date: 2026-02-11 18:39:49.420194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd22e31982add'
down_revision: Union[str, Sequence[str], None] = '751dec83e958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('comapany_email', sa.String(length=255), nullable=False, comment='comapny email'))
    op.drop_column('companies', 'comapny_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('comapny_email', mysql.VARCHAR(length=255), nullable=False, comment='comapny email'))
    op.drop_column('companies', 'comapany_email')
    # ### end Alembic commands ###
