"""changes in table company table add country

Revision ID: dcdb69577453
Revises: d22e31982add
Create Date: 2026-02-13 16:56:09.525267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dcdb69577453'
down_revision: Union[str, Sequence[str], None] = 'd22e31982add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('comapany_country', sa.String(length=50), nullable=False, comment='company country'))
    op.alter_column('companies', 'comapany_email',
               existing_type=mysql.VARCHAR(length=255),
               comment='company email',
               existing_comment='comapny email',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'comapany_email',
               existing_type=mysql.VARCHAR(length=255),
               comment='comapny email',
               existing_comment='company email',
               existing_nullable=False)
    op.drop_column('companies', 'comapany_country')
    # ### end Alembic commands ###
